defaults:
  - base

train:
  task: image_classification
  batch_size: 32
  epochs: 20
  learning_rate: 0.001
  image_size: 224
  num_workers: 8
  weight_decay: 0.0001
  use_class_weights: true
  output_name: train_image_baseline

model:
  image_backbone: mobilenet_v3_small
